# mapping from the data ID's to the map IDs
# no canada - no its 'domestic'
mapMappings =
  argentina: '#m-argentina'
  australia: '#m-australia'
  austria: '#m-austria'
  bahrain: '#m-bahrain'
  belgium: '#m-belgium'
  bolivia: '#m-bolivia'
  brazil: '#m-brazil'
  bulgaria: '#m-bulgaria'
  chile: '#m-chile'
  china: '#m-china'
  cis: '#m-russia'
  colombia: '#m-colombia'
  croatia: '#m-croatia'
  czech: '#m-czech-republic'
  denmark: '#m-denmark'
  ecuador: '#m-ecuador'
  egypt: '#m-egypt'
  estonia: '#m-estonia'
  finland: '#m-finland'
  france: [ '#m-france', '#m-morocco', '#m-tunisia'] #monaco is practically IN france so I'll just leave the map as is
  germany: '#m-germany'
  ghana: '#m-ghana'
  greece: '#m-greece'
  hongkong: '#m-hong-kong'
  hungary: '#m-hungary'
  iceland: '#m-iceland'
  india: '#m-india'
  indonesia: '#m-indonesia'
  israel: '#m-israel'
  italy: '#m-italy'
  japan: '#m-japan'
  kenya: [ '#m-kenya', '#m-uganda', '#m-somalia', '#m-tanzania' ]
  korea: '#m-south-korea'
  latvia: '#m-latvia'
  lebanon: '#m-lebanon'
  lithuania: '#m-lithuania'
  malaysia: '#m-malaysia'
  mexico: '#m-mexico'
  netherlands: '#m-netherlands'
  newzealand: '#m-new-zealand'
  nigeria: '#m-nigeria'
  norway: '#m-norway'
  peru: '#m-peru'
  philippines: '#m-philippines'
  poland: '#m-poland'
  portugal: '#m-portugal'
  romania: '#m-romania'
  serbia: '#m-serbia'
  singapore: '#m-singapore'
  slovakia: '#m-slovakia'
  slovenia: '#m-slovenia'
  southafrica: '#m-south-africa'
  spain: '#m-spain'
  sweden: '#m-sweden'
  taiwan: '#m-taiwan'
  thailand: '#m-thailand'
  turkey: '#m-turkey'
  uae: '#m-uae'
  uk: [ '#m-england', '#m-ireland' ]
  ukraine: '#m-ukraine'
  unitedstates: [ '#m-united-states', '#m-canada' ]
  uruguay: '#m-uruguay'
  venezuela: '#m-venezuela'

module.exports = mapMappings
