fs = require 'fs'
exec = require('child_process').exec

execHandler = (error,stdout,stderr) ->
  console.log stdout
  console.log stderr
  #console.log error if error != null

option '-y','--year [YEAR]', 'Year to build fetchdata with'

task 'fetchdata', 'Get all the data for countries from the website (use --year to specify year).', (options) ->
  if not options.year
    console.log "You need to specify the year: --year 2011"
    return
  console.log "running get_country_list"
  exec "sh bin/get_country_list.sh #{options.year}", execHandler

task 'fetchotherdata', 'Get the data for countries with an alternate format.', (options) ->
  #TODO this isn't working... I've been doing it manual command line style for the moment
  if not options.year
    console.log "You need to specify the year: --year 2011"
    return
  console.log "running get_country_list"
  exclude = ['israel','ecuador','indonesia','uae','bahrain']
  for country in exclude
    exec "sh bin/get_country_from_wk.sh #{country} #{options.year}", execHandler

task 'makeJSON', 'Make all the existing data into JSON', ->
  exec 'mkdir public/data', execHandler
  console.log "building country data..."
  exec 'sh bin/convert_to_json.sh', execHandler
  # TODO verify that the data is actually good standing JSON

task 'makeSummaries', 'Make Overview data - you must run this like this:\n\nNODE_PATH="app" cake makeJSON', ->
  Spine = require 'spine'
  Spine.Model.Local = {}
  Spine.Model.Ajax = {}
  Extractor = require 'lib/extract'
  Movie = require 'models/movie'
  years = [2007..2011]

  console.log "building domestic data..."
  summaryData =
    unitedstates: []
  for year in years
    console.log "#{year}"
    l = (d) =>
      Movie.create({title: d.film?.replace(/"/g,''), hollywood: true, year:d.year, distributor: d.distributor, story:d.story?.replace(/"/g,''),genre:d.genre?.replace(/"/g,''),country:null})
      #console.log "Made movie for '#{d.film}' #{d.year}"
    console.log " - going to parse JSON"
    yearlyData = JSON.parse(fs.readFileSync("public/data/#{year}.json"))
    console.log " - parsed JSON"
    results = Extractor.extractDomesticMovies(yearlyData,'unitedstates',year,l)
    summaryData.unitedstates.push(s) for s in results
    console.log " - extracted movies"

  console.log "\nbuilding INTERNATIONAL data..."
  countries = JSON.parse(fs.readFileSync('public/data/countries.json'))
  # these countries were built using the 'week by week' breakout generated by get_country_from_wk.sh
  alternateformat = ['israel','ecuador','indonesia','uae','bahrain']
  for k,c of countries
    country = c['Country|key'][1]
    summaryData[country] = [] if country not in summaryData
    movieData = []
    console.log "#{country}"
    for year in years
      console.log "  #{year}"
      movieFile = null
      try
        console.log "    - try to parse JSON"
        movieFile = fs.readFileSync("public/data/#{country}/#{year}.json")
        console.log "    - read JSON"
      catch e
        #...
      if movieFile
        movies = JSON.parse(movieFile)
        console.log "    - parsed JSON"
        if country in alternateformat
          console.log "    - converting week format to general format"
          newmovies = {}
          foundmovies = []
          studiokey = ' Studio'
          grosskey = ' Week'
          for k,v of movies
            if v[' TW'] == ' TW'
              # a new CSV header column is here, redefine some cols
              studiokey = null
              studiokey = ' Studio' if v[' Studio'] == ' Studio'
              grosskey = ' Week'
              grosskey = ' Gross-to-Date' if v[ " Change / Avg."] == ' Gross-to-Date'
              grosskey = ' Change / Avg.' if v[ " Screens"] == ' Gross-to-Date'
            else if v[' Movie'] not in foundmovies
              distributor = 'Unknown'
              distributor = v[studiokey] if studiokey?
              #console.log "#{v[' Movie']} = #{v[grosskey]} #{grosskey}"
              newmovies[k] = {" Movie Title": v[' Movie'],"Gross": v[grosskey] , 'Distributor': distributor}
              foundmovies.push v[' Movie']
          movies = newmovies
          #console.log "new movies = #{JSON.stringify(movies)}"
        results = Extractor.extractCountrySummary(movies,Movie,country,year)
        summaryData[country].push(s) for s in results
        console.log "    - read summary data"
        movieData = movieData.concat Extractor.extractCountryMovies(movies,Movie,year)
        console.log "    - read movie data"
    fs.createWriteStream("public/data/#{country}.json").write(JSON.stringify(movieData))
  fs.createWriteStream('public/data/countrysummaries.json').write(JSON.stringify(summaryData))
  #console.log "Summary: #{JSON.stringify(summaryData)}"
